apiVersion: v1
kind: Service
metadata:
  name: myninja-server-svc
  labels:
    app: myninja-server
spec:
  type: ClusterIP
  selector:
    app: myninja-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myninja-server-deployment
  labels:
    app: myninja-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myninja-server
  template:
    metadata:
      labels:
        app: myninja-server
    spec:
      containers:
      - name: myninja-server
        image: ckasidis/myninja-server:latest
        env:
        - name: PG_HOST
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: pg-host
        - name: PG_DATABASE
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: pg-database
        - name: PG_USER
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: pg-user
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: pg-password
        - name: FIREBASE_CRED
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: firebase-cred
        ports:
        - containerPort: 8080
